export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import './globals.css'
import Provider from './provider'
export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Provider>
  )
}
